name: terraform-ci

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: fmt (check)
        run: terraform fmt -check -recursive

      - name: init (no backend)
        run: terraform init -backend=false

      - name: validate
        run: terraform validate
